apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-disk
  namespace: prisma
  labels:
    stage: production
    name: database 
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi