apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dc-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: dc-api
        app: dc
    spec:
      containers:
        - name: dc-api
          image: prismagraphql/prisma:1.34
          ports:
            - name: api-8080
              containerPort: 8080