apiVersion: v1
kind: Service
metadata:
  name: dc-api
  namespace: prisma
  labels:
    app: dc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
  selector:
    stage: production
    name: dc-api
    app: dc