apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  namespace: prisma
  labels:
    stage: production
    name: web
    app: test
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        stage: production
        name: web
        app: test
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.34
          ports:
            - name: prisma-4466
              containerPort: 4466
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG