apiVersion: v1
kind: Service
metadata:
  name: dc-web
  labels:
    app: dc
spec:
  ports:
    - port: 8080
      nodePort: 30002
      protocol: TCP
  selector:
    stage: production
    name: dc-web
    app: dc